#!/bin/sh

#  Merge_difficult_regions.sh
#  
#
#  Created by Zook, Justin on 12/13/16.
#
#  Updated by Zook, Justin on 1/3/19 to make everything reproducible and include v4.1 for HG002

#merge other difficult regions (need to use subtractbed for vdj because it didn't work with multiintersectbed)
/Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/multiIntersectBed -i /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/OtherDifficult/mm-2-merged.bed /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/OtherDifficult/example_of_no_ref_regions_input_file_b37_bedtools_slop_15kb_merged.bed /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/OtherDifficult/hg19.contigs.1-22.lt_500kb.bed /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/OtherDifficult/hs37d5_hg38_minimap2_asm20_N10_gt1contig_gt1kb.bed /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/OtherDifficult/hs37d5_hg38_minimap2_asm20_N10_nocovgt1kb.bed /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/OtherDifficult/L1Hs_gt500.bed /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/OtherDifficult/MHC_GRCh37.bed /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/OtherDifficult/SP_SPonly_primary_assm_alignments_sorted_merged.bed | grep -v 'gl\|hap\|MT' | /Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/mergeBed -i stdin | /Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/subtractBed -a /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/LowComplexity/intermediatefiles/human.b37.genome.bed -b stdin | /Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/subtractBed -a stdin -b /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/OtherDifficult/hg19.vdj.bed | /Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/subtractBed -a /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/LowComplexity/intermediatefiles/human.b37.genome.bed -b stdin | /Volumes/DroboZook/bioinfo/htslib-1.3.2/bgzip -c > /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/OtherDifficult/allOtherDifficultregions.bed.gz
#merge all low mappable and seg dup regions
/Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/multiIntersectBed -i /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/mappability/lowmappabilityall_GRCh38equivalent.bed.gz /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/SegmentalDuplications/hg19.segdups_sorted_merged.bed.gz | grep -v 'gl\|hap\|MT' | /Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/mergeBed -i stdin | /Volumes/DroboZook/bioinfo/htslib-1.3.2/bgzip -c > /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/alllowmapandsegdupregions.bed.gz
/Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/subtractBed -a /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/LowComplexity/intermediatefiles/human.b37.genome.bed -b /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/alllowmapandsegdupregions.bed.gz | /Volumes/DroboZook/bioinfo/htslib-1.3.2/bgzip -c > /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/notinalllowmapandsegdupregions.bed.gz
#merge all difficult regions
/Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/multiIntersectBed -i /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/mappability/lowmappabilityall_GRCh38equivalent.bed.gz /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GCcontent/human_g1k_v37_l100_gclt25orgt65_slop50.bed.gz /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/LowComplexity/AllTandemRepeatsandHomopolymers_slop5.bed.gz /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/SegmentalDuplications/hg19.segdups_sorted_merged.bed.gz /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/FunctionalTechnicallyDifficultRegions/BadPromoters_gb-2013-14-5-r51-s1.bed.gz /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/OtherDifficult/allOtherDifficultregions.bed.gz | grep -v 'gl\|hap\|MT' | /Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/mergeBed -i stdin | /Volumes/DroboZook/bioinfo/htslib-1.3.2/bgzip -c > /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/alldifficultregions.bed.gz

/Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/subtractBed -a /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/LowComplexity/intermediatefiles/human.b37.genome.bed -b /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/alldifficultregions.bed.gz | /Volumes/DroboZook/bioinfo/htslib-1.3.2/bgzip -c > /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/notinalldifficultregions.bed.gz


gunzip -c /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/mappability/lowmappabilityall_GRCh38equivalent.bed.gz | awk '{sum+=$3-$2} END {print sum}' 
#416543137
gunzip -c /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GCcontent/human_g1k_v37_l100_gclt25orgt65_slop50.bed.gz| awk '{sum+=$3-$2} END {print sum}' 
#190576094
gunzip -c /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/LowComplexity/AllTandemRepeatsandHomopolymers_slop5.bed.gz | awk '{sum+=$3-$2} END {print sum}' 
#183352798
gunzip -c /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/SegmentalDuplications/hg19.segdups_sorted_merged.bed.gz | awk '{sum+=$3-$2} END {print sum}' 
#160018336
gunzip -c /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/alldifficultregions.bed.gz | awk '{sum+=$3-$2} END {print sum}' 
#783225244
gunzip -c /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/notinalldifficultregions.bed.gz | awk '{sum+=$3-$2} END {print sum}' 
#2312468737

#merge genomespecific and alldifficultregions
/Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/multiIntersectBed -i /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/alldifficultregions.bed.gz  /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG001_NA12878/GIABv3.3.2/HG001_genomespecific_complexandSVs_v3.3.2_PG_RTG.bed.gz  | /Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/mergeBed -i stdin | /Volumes/DroboZook/bioinfo/htslib-1.3.2/bgzip -c > /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG001_NA12878/HG001_genomespecific_RTG_PG_v3.3.2_SVs_alldifficultregions.bed.gz 
/Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/subtractBed -a /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/LowComplexity/intermediatefiles/human.b37.genome.bed -b /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG001_NA12878/HG001_genomespecific_RTG_PG_v3.3.2_SVs_alldifficultregions.bed.gz | /Volumes/DroboZook/bioinfo/htslib-1.3.2/bgzip -c > /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG001_NA12878/notinHG001_genomespecific_RTG_PG_v3.3.2_SVs_alldifficultregions.bed.gz 

/Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/multiIntersectBed -i /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/alldifficultregions.bed.gz /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG002/GIABv3.3.2/HG002_genomespecific_complexandSVs_v3.3.2.bed.gz  | /Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/mergeBed -i stdin | /Volumes/DroboZook/bioinfo/htslib-1.3.2/bgzip -c > /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG002/GIABv3.3.2/HG002_genomespecific_complexandSVs_alldifficultregions_v3.3.2.bed.gz 
/Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/subtractBed -a /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/LowComplexity/intermediatefiles/human.b37.genome.bed -b /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG002/GIABv3.3.2/HG002_genomespecific_complexandSVs_alldifficultregions_v3.3.2.bed.gz | /Volumes/DroboZook/bioinfo/htslib-1.3.2/bgzip -c > /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG002/GIABv3.3.2/notinHG002_genomespecific_complexandSVs_alldifficultregions_v3.3.2.bed.gz 

/Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/multiIntersectBed -i /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/alldifficultregions.bed.gz /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG002/GIABv4.1/HG002_genomespecific_complexandSVs_v4.1.bed.gz  | /Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/mergeBed -i stdin | /Volumes/DroboZook/bioinfo/htslib-1.3.2/bgzip -c > /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG002/GIABv4.1/HG002_genomespecific_complexandSVs_alldifficultregions_v4.1.bed.gz 
/Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/subtractBed -a /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/LowComplexity/intermediatefiles/human.b37.genome.bed -b /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG002/GIABv4.1/HG002_genomespecific_complexandSVs_alldifficultregions_v4.1.bed.gz | /Volumes/DroboZook/bioinfo/htslib-1.3.2/bgzip -c > /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG002/GIABv4.1/notinHG002_genomespecific_complexandSVs_alldifficultregions_v4.1.bed.gz 

/Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/multiIntersectBed -i /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/alldifficultregions.bed.gz /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG003/GIABv3.3.2/HG003_genomespecific_complexandSVs_v3.3.2.bed.gz  | /Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/mergeBed -i stdin | /Volumes/DroboZook/bioinfo/htslib-1.3.2/bgzip -c > /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG003/GIABv3.3.2/HG003_genomespecific_complexandSVs_alldifficultregions_v3.3.2.bed.gz 
/Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/subtractBed -a /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/LowComplexity/intermediatefiles/human.b37.genome.bed -b /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG003/GIABv3.3.2/HG003_genomespecific_complexandSVs_alldifficultregions_v3.3.2.bed.gz | /Volumes/DroboZook/bioinfo/htslib-1.3.2/bgzip -c > /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG003/GIABv3.3.2/notinHG003_genomespecific_complexandSVs_alldifficultregions_v3.3.2.bed.gz 

/Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/multiIntersectBed -i /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/alldifficultregions.bed.gz /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG004/GIABv3.3.2/HG004_genomespecific_complexandSVs_v3.3.2.bed.gz  | /Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/mergeBed -i stdin | /Volumes/DroboZook/bioinfo/htslib-1.3.2/bgzip -c > /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG004/GIABv3.3.2/HG004_genomespecific_complexandSVs_alldifficultregions_v3.3.2.bed.gz 
/Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/subtractBed -a /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/LowComplexity/intermediatefiles/human.b37.genome.bed -b /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG004/GIABv3.3.2/HG004_genomespecific_complexandSVs_alldifficultregions_v3.3.2.bed.gz | /Volumes/DroboZook/bioinfo/htslib-1.3.2/bgzip -c > /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG004/GIABv3.3.2/notinHG004_genomespecific_complexandSVs_alldifficultregions_v3.3.2.bed.gz 

/Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/multiIntersectBed -i /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/alldifficultregions.bed.gz /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG005/GIABv3.3.2/HG005_genomespecific_complexandSVs_v3.3.2.bed.gz  | /Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/mergeBed -i stdin | /Volumes/DroboZook/bioinfo/htslib-1.3.2/bgzip -c > /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG005/GIABv3.3.2/HG005_genomespecific_complexandSVs_alldifficultregions_v3.3.2.bed.gz 
/Volumes/DroboZook/bioinfo/bedtools2.25.0/bin/subtractBed -a /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/LowComplexity/intermediatefiles/human.b37.genome.bed -b /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG005/GIABv3.3.2/HG005_genomespecific_complexandSVs_alldifficultregions_v3.3.2.bed.gz | /Volumes/DroboZook/bioinfo/htslib-1.3.2/bgzip -c > /Volumes/giab/analysis/benchmarking-tools/resources/stratification-bed-files/GenomeSpecific/HG005/GIABv3.3.2/notinHG005_genomespecific_complexandSVs_alldifficultregions_v3.3.2.bed.gz 
