## GIAB genome
giab_sample: "HG007"

## reference information
ref :
    version : "GRCh38"
    fasta_url : ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz

## benchmark information
benchmark :
    version : "v4.2.1"
    vcf_gz : resources/benchmark/HG007_GRCh38_1_22_v4.2.1_benchmark_before_PS_remove.vcf.gz
    vcf_gz_tbi : resources/benchmark/HG007_GRCh38_1_22_v4.2.1_benchmark_before_PS_remove.vcf.gz.tbi

## rule input dependency files
input_files:
    rule7 :
        ["resources/input_files/GRCh38/sorted_GRCh38_HG007_GIABv4.2.1_CNV_mrcanavarIllumina_CCShighcov_ONThighcov_intersection.bed",
        "resources/input_files/GRCh38/sorted_GRCh38_HG007_GIABv4.2.1_SV_pbsv_slop25percent.bed",
        "resources/input_files/GRCh38/sorted_GRCh38_HG007_GIABv4.2.1_CNV_CCSandONT_elliptical_outlier.bed",
        "resources/input_files/GRCh38/sorted_HG005_GRCh38_union_SVs_repeatexpanded_slop50_merge1000_expanded_150_percent.bed",
        "resources/input_files/GRCh38/sorted_HG005_GRCh38_inversions_slop150_chr1_22.bed"]

    rule9 : resources/input_files/GRCh38/GRCh38_alldifficultregions.bed.gz
    rule10 : resources/input_files/GRCh38/human.b38.genome.bed
