## GIAB genome
giab_sample: "HG005"

## reference information
ref :
    version : "GRCh38"
    fasta_url : ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz

## benchmark information
benchmark :
    version : "v4.2.1"
    vcf_gz : resources/benchmark/HG005_GRCh38_1_22_v4.2.1_benchmark_hifiasm_v11_phasetransfer.vcf.gz
    vcf_gz_tbi : resources/benchmark/HG005_GRCh38_1_22_v4.2.1_benchmark_hifiasm_v11_phasetransfer.vcf.gz.tbi

## rule input dependency files
input_files:
    rule7 :
        ["resources/input_files/GRCh38/sorted_HG005_GRCh38_mrcanavar_intersect_PacBio_HiFi_1000_window_size_cnv_threshold_intersect_ONT_1000_window_size_cnv_threshold.bed",
        "resources/input_files/GRCh38/sorted_HG005_GRCh38_union_SVs_repeatexpanded_slop50_merge1000_expanded_150_percent.bed",
        "resources/input_files/GRCh38/sorted_HG005_GRCh38_union_PacBio_HiFi_ONT_1000_window_size_combined_elliptical_outlier_threshold.bed",
        "resources/input_files/GRCh38/sorted_HG005_GRCh38_inversions_slop150_chr1_22.bed"]
    rule9 : resources/input_files/GRCh38/GRCh38_alldifficultregions.bed.gz
    rule10 : resources/input_files/GRCh38/human.b38.genome.bed
